/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criminales;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author lenovo
 */
public class FrameEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FrameEmpresa() {
        initComponents();
        
        
        
        ImageIcon img = new  ImageIcon("src\\img\\NOTIFICACIONES\\notificaciones.png");
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(notificaciones.getWidth(), notificaciones.getHeight(), Image.SCALE_DEFAULT));
        notificaciones.setIcon(icono);
        
        ImageIcon PRISION = new  ImageIcon("src\\img\\NOTIFICACIONES\\PRISION.png");
        Icon PRISIONES = new ImageIcon(PRISION.getImage().getScaledInstance(pri.getWidth(), pri.getHeight(), Image.SCALE_DEFAULT));
        pri.setIcon(PRISIONES);
        
        ImageIcon CON = new  ImageIcon("src\\img\\NOTIFICACIONES\\CONFERENCIA.png");
        Icon CONGRE = new ImageIcon(CON.getImage().getScaledInstance(CONGRESO.getWidth(), CONGRESO.getHeight(), Image.SCALE_DEFAULT));
        CONGRESO.setIcon(CONGRE);
        
        ImageIcon SO = new  ImageIcon("src\\img\\NOTIFICACIONES\\SOCIO.png");
        Icon SOCI = new ImageIcon(SO.getImage().getScaledInstance(SOCIO.getWidth(), SOCIO.getHeight(), Image.SCALE_DEFAULT));
        SOCIO.setIcon(SOCI);
        
        ImageIcon CRI = new  ImageIcon("src\\img\\NOTIFICACIONES\\CRIMINAL.png");
        Icon CRIMI = new ImageIcon(CRI.getImage().getScaledInstance(CRIMINAL.getWidth(), CRIMINAL.getHeight(), Image.SCALE_DEFAULT));
        CRIMINAL.setIcon(CRIMI);
        
        ImageIcon RE = new  ImageIcon("src\\img\\NOTIFICACIONES\\REDCRIMINAL.png");
        Icon REDCRIMINAL = new ImageIcon(RE.getImage().getScaledInstance(RED.getWidth(), RED.getHeight(), Image.SCALE_DEFAULT));
        RED.setIcon(REDCRIMINAL);
        
        ImageIcon SER = new  ImageIcon("src\\img\\NOTIFICACIONES\\RESPUESTA24HRS.png");
        Icon SERVI = new ImageIcon(SER.getImage().getScaledInstance(SERVICIO.getWidth(), SERVICIO.getHeight(), Image.SCALE_DEFAULT));
        SERVICIO.setIcon(SERVI);
        
        ImageIcon DE = new  ImageIcon("src\\img\\NOTIFICACIONES\\DELITOS.png");
        Icon DEL = new ImageIcon(DE.getImage().getScaledInstance(DELITO.getWidth(), DELITO.getHeight(), Image.SCALE_DEFAULT));
        DELITO.setIcon(DEL);
        
        this.repaint();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jlLupa = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        notificaciones = new javax.swing.JButton();
        pri = new javax.swing.JButton();
        CONGRESO = new javax.swing.JButton();
        SOCIO = new javax.swing.JButton();
        CRIMINAL = new javax.swing.JButton();
        RED = new javax.swing.JButton();
        SERVICIO = new javax.swing.JButton();
        DELITO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 5260, 2590));
        jPanel3.add(jlLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 30, 30));
        jPanel3.add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 120, 90));

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("DE POLICIA");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("B & B");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("DEPARTAMENTO");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        notificaciones.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        notificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notificaciones.setFocusable(false);
        notificaciones.setOpaque(false);
        notificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificacionesActionPerformed(evt);
            }
        });
        jPanel3.add(notificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 210, 130));

        pri.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        pri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pri.setFocusable(false);
        pri.setOpaque(false);
        pri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priActionPerformed(evt);
            }
        });
        jPanel3.add(pri, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 210, 130));

        CONGRESO.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        CONGRESO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CONGRESO.setFocusable(false);
        CONGRESO.setOpaque(false);
        CONGRESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONGRESOActionPerformed(evt);
            }
        });
        jPanel3.add(CONGRESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 210, 130));

        SOCIO.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        SOCIO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SOCIO.setFocusable(false);
        SOCIO.setOpaque(false);
        SOCIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOCIOActionPerformed(evt);
            }
        });
        jPanel3.add(SOCIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 210, 130));

        CRIMINAL.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        CRIMINAL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CRIMINAL.setFocusable(false);
        CRIMINAL.setOpaque(false);
        CRIMINAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRIMINALActionPerformed(evt);
            }
        });
        jPanel3.add(CRIMINAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 210, 130));

        RED.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        RED.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RED.setFocusable(false);
        RED.setOpaque(false);
        RED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REDActionPerformed(evt);
            }
        });
        jPanel3.add(RED, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 210, 130));

        SERVICIO.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        SERVICIO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SERVICIO.setFocusable(false);
        SERVICIO.setOpaque(false);
        SERVICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SERVICIOActionPerformed(evt);
            }
        });
        jPanel3.add(SERVICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 210, 130));

        DELITO.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        DELITO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DELITO.setFocusable(false);
        DELITO.setOpaque(false);
        DELITO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELITOActionPerformed(evt);
            }
        });
        jPanel3.add(DELITO, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 210, 130));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -80, -1, -1));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 1140, 710));

        jLabelFondo.setIcon(new javax.swing.ImageIcon("E:\\elchido\\Criminales\\src\\img\\MUNDO-01.png")); // NOI18N
        jPanel3.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1140, 710));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SALIR");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 670, 110, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1144, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priActionPerformed
        String c="pri";
        new FramePrincipal(c).setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_priActionPerformed

    private void notificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificacionesActionPerformed
       String c="notificaciones";
        new FramePrincipal(c).setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_notificacionesActionPerformed

    private void CONGRESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONGRESOActionPerformed
    String c="CONGRESO";
        new FramePrincipal(c).setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CONGRESOActionPerformed

    private void SOCIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOCIOActionPerformed
    String c="SOCIO";
        new FramePrincipal(c).setVisible(true);
        this.dispose();;// TODO add your handling code here:
    }//GEN-LAST:event_SOCIOActionPerformed

    private void CRIMINALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRIMINALActionPerformed
    String c="CRIMINAL";
        new FramePrincipal(c).setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CRIMINALActionPerformed

    private void REDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REDActionPerformed
        String c="RED";
        new FramePrincipal(c).setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_REDActionPerformed

    private void SERVICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SERVICIOActionPerformed
    String c="SERVICIO";
        new FramePrincipal(c).setVisible(true);
        this.dispose();;// TODO add your handling code here:
    }//GEN-LAST:event_SERVICIOActionPerformed

    private void DELITOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELITOActionPerformed
        String c="DELITO";
        new FramePrincipal(c).setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_DELITOActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (!"DarkWindows".equals(info.getName())) {
                } else {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONGRESO;
    private javax.swing.JButton CRIMINAL;
    private javax.swing.JButton DELITO;
    private javax.swing.JButton RED;
    private javax.swing.JButton SERVICIO;
    private javax.swing.JButton SOCIO;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JLabel jlLupa;
    private javax.swing.JButton notificaciones;
    private javax.swing.JButton pri;
    // End of variables declaration//GEN-END:variables
}
